[tool.poetry]
name = "hugo-ext-status"
version = "1.0.1"
description = "Bot status middleware for Hugo"
authors = ["Nariman Safiulin <woofilee@gmail.com>"]
license = "MIT"

readme = "README.md"
repository = "https://github.com/Roolat/hugo-ext-status"

keywords = ["discord", "bot", "hugo"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Natural Language :: Russian",
    "Operating System :: OS Independent",
]

packages = [
    { include = "hugo" },
]

[tool.poetry.dependencies]
python = "^3.6"
"discord.py" = "^1.0.0a"
hugo = "^0.5.0"
pendulum = "^2.0"

[tool.black]
line-length = 80
py36 = true
